cacheFolder: ./.yarn/cache
enableGlobalCache: false
injectEnvironmentFiles:
  - .env?
nodeLinker: node-modules
npmScopes:
  "share-meals":
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_PAT}"
    npmRegistryServer: https://npm.pkg.github.com
